# Generated by Django 3.0.2 on 2020-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('Rname', models.CharField(max_length=100)),
                ('Ingredients', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='Rcp_Images')),
                ('steps', models.CharField(max_length=1000)),
            ],
        ),
    ]
