# Generated by Django 3.0.2 on 2020-02-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcp',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
    ]
