# Generated by Django 3.0.2 on 2020-02-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_rcp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcp',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
