# Generated by Django 3.0.2 on 2020-02-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_auto_20200204_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcp',
            name='image',
            field=models.ImageField(blank=True, upload_to='Rcp_Images'),
        ),
    ]
