# Generated by Django 3.0.2 on 2020-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_auto_20200204_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcp',
            name='steps',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
